<?php
include "include.php";
use Stripe\Event as WebhookEvent;

$webhook_response = '{"id":"evt_1KV9hh2Hy5b36ua7FDEp7HNk","object":"event","account":"acct_1KV9Lv2Hy5b36ua7","api_version":"2017-04-06","created":1645341573,"data":{"object":{"id":"acct_1KV9Lv2Hy5b36ua7","object":"account","capabilities":{"afterpay_clearpay_payments":"active","au_becs_debit_payments":"active","bancontact_payments":"active","card_payments":"active","eps_payments":"active","giropay_payments":"active","ideal_payments":"active","p24_payments":"active","sepa_debit_payments":"active","sofort_payments":"active","platform_payments":"active"},"charges_enabled":true,"controller":{"type":"application","is_controller":true},"country":"AU","default_currency":"aud","details_submitted":true,"email":"oliveorg1@yopmail.com","payouts_enabled":false,"type":"standard","business_logo":null,"business_logo_large":null,"business_name":"Olive Event booking","business_primary_color":null,"business_url":"https:\/\/www.eventbookings.com\/","debit_negative_balances":true,"display_name":"Eventbookings","external_accounts":{"object":"list","data":[{"id":"ba_1KV9cD2Hy5b36ua7mmUmyd8j","object":"bank_account","account":"acct_1KV9Lv2Hy5b36ua7","account_holder_name":null,"account_holder_type":null,"account_type":null,"available_payout_methods":["standard"],"bank_name":"STRIPE TEST BANK","country":"AU","currency":"aud","default_for_currency":true,"fingerprint":"yXROs1ZWfcF9vdvD","last4":"3456","metadata":[],"routing_number":"11 0000","status":"new"}],"has_more":false,"total_count":1,"url":"\/v1\/accounts\/acct_1KV9Lv2Hy5b36ua7\/external_accounts"},"future_verification":{"disabled_reason":null,"due_by":null,"errors":[],"fields_needed":[],"pending_verification":[]},"managed":false,"mcc":"5734","metadata":[],"payout_schedule":{"delay_days":2,"interval":"daily"},"payout_statement_descriptor":null,"statement_descriptor":"WWW.EVENTBOOKINGS.COM","statement_descriptor_kana":null,"statement_descriptor_kanji":null,"statement_descriptor_prefix":"DAF","support_address":null,"support_email":null,"support_phone":"+8801913010534","support_url":null,"timezone":"Etc\/UTC","verification":{"disabled_reason":"fields_needed","due_by":null,"errors":[{"code":"verification_failed_keyed_identity","reason":"The identity information you entered cannot be verified. Please correct any errors or upload a document that matches the identity fields (e.g., name and date of birth) that you entered.","requirement":"legal_entity.verification.document"}],"fields_needed":["legal_entity.verification.document"],"pending_verification":[]}},"previous_attributes":{"verification":{"errors":[],"fields_needed":[],"pending_verification":["legal_entity.verification.document"]}}},"livemode":false,"pending_webhooks":1,"request":null,"type":"account.updated","user_id":"acct_1KV9Lv2Hy5b36ua7"}';
$webhook_data = json_decode($webhook_response, true);
if ($webhook_data['type'] == WebhookEvent::ACCOUNT_UPDATED) {
}
$stripe_account_id = $webhook_data['account'];
$data_object = $webhook_data['data']['object'];
$email = $data_object['email'];
echo "<pre>";
print_r($data_object["charges_enabled"]);
echo "</pre>";